[project]
name = "time-mcp"
version = "0.1.0"
description = "MCP server for the time (and date)"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.4.1",
]
